name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: |
          mkdir -p release_out
          find app/build/outputs/apk/ -name "*.apk" -exec cp {} release_out/phed_update.apk \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_out/phed_update.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}